apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: cbt-namespace
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: cbt-namespace
spec:
  selector:
    app: adminer
  ports:
  - port: 8089
    targetPort: 8080
  type: LoadBalancer

