kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-role-binding # This is the role binding that will bind the service account to the role
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole # This is the role that Traefik will use to access the Kubernetes API
  name: traefik-role
subjects:
  - kind: ServiceAccount
    name: traefik-account
    namespace: default