apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: default
data:
  config.yaml: | # This is the Traefik configuration file
    http:
      services:
        service:
          loadBalancer:
            sticky:
              cookie: {}
    entryPoints:
      web:
        address: ":80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik   
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.2 # This is the Traefik image that will be used to create the Traefik pod
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          args:
            - --api.insecure=true
            - --providers.file.filename=/etc/traefik/config.yaml
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/traefik
      volumes:
        - name: config
          configMap:
            name: traefik-config
