apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: cbt-namespace
data:
  config.yaml: |
    http:
      services:
        service:
          loadBalancer:
            sticky:
              cookie: {}
    entryPoints:
      web:
        address: ":80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: cbt-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik   
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.2
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          args:
            - --api.insecure=true
            - --providers.file.filename=/etc/traefik/config.yaml
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/traefik
      volumes:
        - name: config
          configMap:
            name: traefik-config
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: cbt-namespace
  annotations:
  ## code yang menuju keberhasilan
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: cookie
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "example"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "60"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httpOnly: "true"
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: traefik
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: cbt-namespace
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: traefik
  type: LoadBalancer